from typing import Protocol
from control_plane.domain.models import ApprovalRequest, ApprovalDecision, ApprovalGrant, ToolRequest

class ApprovalStore(Protocol):
    def create_request(self, request: ApprovalRequest) -> ApprovalRequest: ...
    def get_request(self, approval_id: str) -> ApprovalRequest: ...
    def get_grant(self, approval_id: str) -> ApprovalGrant | None: ...
    def resolve(self, decision: ApprovalDecision) -> ApprovalRequest: ...
    def get_pending_for_task(self, task_id: str) -> list[ApprovalRequest]: ...
    def wait_for_resolution(self, approval_id: str, timeout_seconds: float) -> ApprovalRequest: ...

class ApprovalAuthorizer(Protocol):
    def authorize(self, request: ToolRequest, approval_id: str) -> bool: ...
