from typing import Protocol
from control_plane.domain.models import ApprovalRequest, ApprovalDecision

class ApprovalStore(Protocol):
    def create_request(self, request: ApprovalRequest) -> ApprovalRequest: ...
    def get_request(self, approval_id: str) -> ApprovalRequest: ...
    def resolve(self, decision: ApprovalDecision) -> ApprovalRequest: ...
    def get_pending_for_task(self, task_id: str) -> list[ApprovalRequest]: ...
